# Generated by Django 3.2 on 2025-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.CharField(max_length=36),
        ),
    ]
